# Generated by Django 4.1.7 on 2023-03-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('projectImage', models.ImageField(null=True, upload_to='assets/')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
