# Generated by Django 4.1.7 on 2023-03-03 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0002_projects_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='projectImage',
            field=models.ImageField(null=True, upload_to='portfolioApp/static/assets/'),
        ),
    ]
