# Generated by Django 4.1.7 on 2023-03-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0003_alter_projects_projectimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='projectImage',
            new_name='project_image',
        ),
        migrations.AlterField(
            model_name='projects',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(default='', max_length=1000)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.projects', to_field='title')),
            ],
        ),
    ]
