# Generated by Django 4.1.7 on 2023-03-04 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0004_rename_projectimage_projects_project_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_image',
            field=models.ImageField(null=True, upload_to='staticfiles/assets/'),
        ),
    ]
