# Generated by Django 4.1.7 on 2023-03-07 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0005_alter_projects_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectentry',
            name='project_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioApp.projects'),
        ),
    ]
