# Generated by Django 4.1.7 on 2023-03-07 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0006_alter_projectentry_project_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectentry',
            name='project_name',
        ),
    ]
