# Generated by Django 4.1.7 on 2023-03-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioApp', '0007_remove_projectentry_project_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectEntry',
        ),
    ]
